name: aws-ecr-credential-provider
on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true 
      - name:  Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build binary
        shell: bash
        run: make all
      - name: Output
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: out
          if-no-files-found: error
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      REGISTRY: ${{ secrets.REGISTRY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true 
      - name:  Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: out
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.prep.outputs.tag }}
          name: Release ${{ steps.prep.outputs.tag }}
          draft: false
          files: |
            out/ecr-credential-provider-amd64
            out/ecr-credential-provider-arm64
            out/ecr-credential-provider.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.      
